version: 2

jobs:
  build:
    working_directory: ~/work
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt update
      - run: apt install -y git python3-pip enchant
      - run: pip3 install -U pytest pytest-cov black flake8
      - checkout
      - run: pip3 install .
      # format & lint
      - run: black --check setup.py betterbib/ test/*.py tools/betterbib-dedup-doi tools/betterbib-doi2bibtex tools/betterbib-format tools/betterbib-journal-abbrev tools/betterbib-sync tools/bibitems2bibtex
      - run: flake8 setup.py betterbib/ test/*.py tools/betterbib-dedup-doi tools/betterbib-doi2bibtex tools/betterbib-format tools/betterbib-journal-abbrev tools/betterbib-sync tools/bibitems2bibtex
      # add some entries to the dict
      - run: mkdir -p ~/.config/betterbib/ && echo -e "[DICTIONARY]\nadd=Magnus,Peano,Kutta,Runge,Hermitian,Jacobian\nremove=hermitian" > ~/.config/betterbib/config.ini
      # The tests
      - run: cd test/ && pytest --maxfail=1 --cov betterbib
      # submit to codecov
      - run: apt install -y curl
      - run: bash <(curl -s https://codecov.io/bash)
